### ISSUE TITLE
reproduce the experiment

### ISSUE THREAD

**Issue by saysth** [DIAGNijmegen/neural-odes-segmentation#12] opened 2020-12-09 07:55 UTC
dear sir, I used "best_border_unode_paper.pt" you provided to calculate the metrics but got the following results:
ObjectDice: 0.8760835649486125 A 0.8871834019226542 B 0.8427840540264875
Hausdorff: 375.8985666986306 A 395.2071020096662 B 317.9729607655239
F1: 0.7598035152929279 A 0.7879507931885837 B 0.6753616816059601
it can't match the results in your paper, how can i solve it?

**Comment by hanspinckaers** [comment] 2021-03-18 18:45
Hi @saysth, since other people reproduced this already, I'm gonna close this issue. Please let me know if you have further questions!

**Closed as completed by hanspinckaers** 2021-03-18 18:45 UTC
